name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CyberShield.csproj

    - name: Build
      run: dotnet build CyberShield.csproj --configuration ${{ matrix.configuration }} --no-restore

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CyberShield-${{ matrix.configuration }}
        path: bin/${{ matrix.configuration }}/
